- name: See if rachel content is installed
  stat: path="{{ rachel_content_path }}/index.php"
  register: rachel_content

- name: Set rachel_content_found to False
  set_fact:
     rachel_content_found: False

- name: Set rachel_content_found True if found
  set_fact:
     rachel_content_found: True
  when: rachel_content.stat.exists  == true

- include: rachel_enabled.yml
  when: rachel_enabled and rachel_content_found

- name: Add rachel to service list
  ini_file: dest='{{ service_filelist }}'
            section=rachel
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
    - option: name
      value: rachel
    - option: description
      value: "Educational resources, packaged together for download and distribution in places without internet."
    - option: path
      value: "{{ rachel_content_path }}"
    - option: content_found
      value: "{{ rachel_content_found }}"
    - option: enabled
      value: "{{ rachel_enabled }}"
