- name: See if rachel content is installed
  stat: path="{{ rachel_content_path }}/index.html
  register: rachel_content
  
- name: Set rachel_content_found  
  set_fact:
     rachel_content_found: '{{ rachel_content.stat.exists }}'     
  
- include: rachel_enabled.yml
  when: rachel_enabled and rachel_content_found                                             