- name: Create link to rachel from doc root
  file: src={{ rachel_content_path }}
        dest={{ rachel_doc_root }}
        owner=root
        group=admin
        state=link

- name: Create link to rachel mysql db from mysql data dir
  file: src={{ rachel_mysqldb_path }}
        dest=/var/lib/mysql/sphider_plus
        owner=root
        group=admin
        state=link

- name: Set mysql password
  lineinfile: regexp=mysql_password1
              line="$mysql_password1 = '{{ mysql_root_password }}';"
              state=present
              dest={{ rachel_content_path }}/rsphider/settings/database.php

- name: Restart mysqld service
  service: name={{ mysql_service }}
           state=restarted



- name: Restart httpd service
  service: name=httpd
           state=restarted
