---
- name: Install required packages
  yum: name={{ item }}
       state=installed
  with_items:
    - vnstat

- name: create database for wan to collect vnstat data
  shell: vnstat -i {{ xsce_wan_device }}
  tags: 
    - network

- name: create database for lan to collect vnstat data
  shell: vnstat -i {{ xsce_lan_device }}
  tags: 
    - network
  when: not xsce_lan_device == ""

- name: put the config file in place
  template: src=vnstat.conf.j2 dest=/etc/vnstat.conf mode=0744 owner=root >
            group=root

- name: start vnstat daemon via systemd
  service: vnstat enabled=yes state=started


