# Assume all XOs are F18 and nothing else is

- name: Install dependent packages non-F18
  yum: name={{ item }}
       state=installed
  with_items:
    - python-selenium
    - python-psutil
    - expect
  tags:
    - download
  when: xo_model == "none"

- name: Install dependent packages F18
  yum: name={{ item }}
       state=installed
  with_items:
    - python-psutil
    - expect
  tags:
    - download
  when: xo_model != "none"

- name: Download dependent pip packages F18
  pip: name=selenium
       extra_args="--download {{ pip_packages_dir }}"
  when: not {{ use_cache }} and not {{ no_network }} and xo_model != "none"
  tags:
    - download2

- name: Install dependent pip packages F18
  pip: name=selenium
       extra_args="--no-index --find-links=file://{{ pip_packages_dir }}"
  when: xo_model != "none"

- name: Install missing packages required for kalite startup
  yum: name={{ item }}
       state=installed
  with_items:
    - lsb
  tags:
    - download
  when: not {{ use_cache }} and not {{ no_network }} and ansible_distribution == "CentOS"

- name: Download the latest kalite repo
  git: repo={{ kalite_repo_url }}
       dest={{ downloads_dir }}/ka-lite
       depth=1
       version="0.13.x"
  when: not {{ use_cache }}
  tags:
    - download2

- name: See if kalite is installed
  stat: path="{{ kalite_root }}/kalite/database/data.sqlite"
  register: kalite_installed

- include: install.yml
  when: not kalite_installed.stat.exists == True

- include: enable.yml

- name: Add kalite to service list
  ini_file: dest='{{ service_filelist }}'
            section=kalite
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
    - option: name
      value: kalite
    - option: description
      value: '"KA-Lite is a server to present Khan Academy videos offline and to download them."'
    - option: path
      value: "{{ kalite_root }}"
    - option: server_name
      value: "{{ kalite_server_name }}"
    - option: port
      value: "{{ kalite_server_port }}"
    - option: enabled
      value: "{{ kalite_enabled }}"
    - option: cron_enabled
      value: "{{ kalite_cron_enabled }}"
