- hosts: 127.0.0.1
  user: root
  connection: local
  tasks:
    - name: run ansible facts
      xsce_facts:

#    - include: tasks/install-xs.yml
#    - include: tasks/idmgr.yml
    - include: tasks/network.yml

