- hosts: 127.0.0.1
  user: root
  connection: local
  vars:
  vars_files:
  - vars/default_vars.yml
  - vars/shaper.yml 
  tasks:
    - name: copy wshaper service script
      template: src=templates/shaper/wshaper.service
                dest=/etc/systemd/system/wshaper.service
                mode=0755

    - name: copy wshaper script
      template: src=templates/shaper/wshaper.j2
                dest=/etc/sysconfig/wshaper
                owner=root
                group=root
                mode=0755

