- name: Install monit package
  yum: name=monit
       state=present
  tags:
    - download

- name: Update main config file 
  template: backup=yes
            src=monitrc
            dest=/etc/monitrc
            owner=root
            group=root
            mode=0600

- name: Update config files
  template: backup=yes
            src={{ item }}
            dest=/etc/monit.d/{{ item }}
            owner=root
            group=root
            force=yes
            mode=0755
  with_items: $watchdog

#TODO: create systemd script
- name: Enable monit service
  command: chkconfig monit on

#- name: Restart monit service
#  command: service monit restart

