- name: Install common packages
  yum: name=$item
       state=present
  with_items:
   - createrepo
   - acpid
   - mlocate
   - mtd-utils
   - rsync
   - htop
   - etckeeper

- name: Keep yum cache
  ini_file: dest=/etc/yum.conf
            section=main
            option=keepcache
            value=1

- name: Keep docs wheninstalling packages
  lineinfile: dest=/etc/rpm/macros.imgcreate
              regexp='^%_excludedocs'
              line='%_excludedocs 0'
              state=present

- name: Disable root login with password 
  lineinfile: dest=/etc/ssh/sshd_config
              regexp='^PermitRootLogin'
              line='^PermitRootLogin without-password'
              state=present
#TODO: use handler to reload ssh

- name: Disable selinux
  selinux: policy=targeted
           state=permissive
#TODO: check logs for selinux issues, and enable it

- name: Enable common services
  service: name=$item
           enabled=yes
           state=started
  with_items:
    - sshd
    
