- name: Install ejabberd packages
  yum: name=${item}
       state=installed
  with_items:
   - ejabberd
- name: Configure ejabberd
  template: src=${item.src}
            dest=${item.dest}
            owner=root
            group=root
            mode=${item.mode}
  with_items:
    - { src: 'ejabberd/ejabberd-xs.cfg.j2', dest: '/etc/ejabberd/ejabberd-xs.cfg' , mode: '0644' }
    - { src: 'ejabberd/ejabberd-xs', dest: '/etc/sysconfig/ejabberd-xs', mode: '0755' }
    - { src: 'ejabberd/ejabberd-xs.init', dest: '/etc/init.d/ejabberd-xs', mode: '0755' }
#    - { src: 'ejabberd/ejabberd', dest: '/etc/sysconfig/olpc-scripts/domain_config.d/ejabberd' , mode: '0755' }
    - { src: 'ejabberd/ejabberd-xs.service.j2', dest: '/etc/systemd/system/ejabberd-xs.service', mode: '0644' }
    - { src: 'ejabberd/xs-ejabberd-srg', dest: '/usr/bin/xs-ejabberd-srg' , mode: '0644' }
    - { src: 'ejabberd/10-ejabberdmoodle', dest: '/usr/share/xs-config/cfg/etc/sudoers.d/10-ejabberdmoodle', mode: '0644' }

- name: Enable ejabberd service
  service: name=ejabberd-xs
           enabled=yes
