- name: Install idmgr package
  yum: name=idmgr
      state=installed
- name: Configure idmgr 
  template: src=files/idmgr/idmgr.conf.j2
            dest=/etc/idmgr.conf
            owner=root
            group=root
            mode=0644
  with_items:
   - { src: 'idmgr/idmgr.conf.j2', dest: '/etc/idmgr.conf' }
   - { src: 'idmgr/idmgr.service', dest: '/etc/systemd/system/idmgr.service' }

- name: Enable idmgr service
  service: name=idmgr
           enabled=yes
           state=started
