- name: Install idmgr packages
  yum: name=${item}
       state=installed
  with_items:
   - ds-backup-server
   - idmgr
   - xinetd
   - xs-rsync
- name: Configure idmgr
  template: src=${item.src}
            dest=${item.dest}
            owner=root
            group=root
            mode=0644
  with_items:
    - { src: 'idmgr/idmgr', dest: '/etc/idmgr.conf' }
    - { src: 'idmgr/idmgr.service.j2', dest: '/etc/systemd/system/idmgr.service' }

- name: Configure ds-backup
  command: /etc/sysconfig/olpc-scripts/setup.d/ds-backup
          creates=/etc/incron.d/ds-backup.conf

- name: Configure idmgr sqlite db
  command: /etc/sysconfig/olpc-scripts/setup.d/idmgr
           creates=/home/idmgr/identity.db

- name: Configure xs-rsync
  command: /etc/sysconfig/olpc-scripts/setup.d/xs-rsync
          creates=/etc/xinetd.d/xs-rsyncd
- name: Enable idmgr service
  service: name=$item
           enabled=yes
           state=started
  with_items:
    - idmgr
    - xinetd
