- name: Install idmgr package
  yum: name=idmgr
      state=installed
- name: Configure idmgr 
  template: src=files/idmgr/idmgr.conf.j2
            dest=/etc/idmgr.conf
            owner=root
            group=root
            mode=0644
- name: Create systemd service file
  copy: src=files/idmgr/idmgr.service
        dest=/etc/systemd/system/idmgr.service
        owner=root
        group=root
        mode=0644
- name: Enable idmgr service
  service: name=idmgr
           enabled=yes
           state=started
