- name: Install monit package
  yum: name=monit
       state=present
- name: Update config files
  copy: src=files/monit.d/$item dest=/etc/monit.d/$item 
  with_items: $watchdog
  register: monit_config
- name: Enable monit service
  command: chkconfig monit on
  only_if: ${monit_config.changed}
- name: Restart monit service
  command: service monit restart
  only_if: ${monit_config.changed}
