---
- name: Install moodle required packages
  yum: name=moodle-xs
       state=installed

- name: Configure moodle
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
    - src=010-make-moodle-default.conf.in
      dest=/etc/httpd/conf.d/010-make-moodle-default.conf
      mode=0655
    - src=moodle-xs.service.in
      dest=/etc/systemd/system/moodle-xs.service
      mode=0655
    - src=moodle-xs-init
      dest=/usr/libexec/moodle-xs-init
      mode=0755

- name: Restart https
  service: name=httpd
           state=restarted

- name: Execute moodle startup script
  command: name=/usr/libexec/moodle-xs-init

- name: Enable moodle service
  service: name=moodle-xs
           enabled=yes
           status=started
