- name: Install named packages
  yum: name=${item}
       state=installed
  with_items:
   - bind
   - bind-utils
- name: Configure named
  template: src=${item.src}
            dest=${item.dest}
            owner=root
            group=root
            mode=0644
  with_items:
    - { src: 'named/named-xs.conf.j2', dest: '/etc/named-xs.conf' }
    - { src: 'named/named.j2', dest: '/etc/sysconfig/named' }
    - { src: 'named/named', dest: '/etc/sysconfig/olpc-scripts/domain_config.d/named' }
    - { src: 'named/localdomain.zone', dest: '/var/named-xs/localdomain.zone' }
    - { src: 'named/localhost.zone', dest: '/var/named-xs/localhost.zone' }
    - { src: 'named/named.broadcast', dest: '/var/named-xs/named.broadcast' }
    - { src: 'named/named.ip6.local', dest: '/var/named-xs/named.ip6.local' }
    - { src: 'named/named.local', dest: '/var/named-xs/named.local' }
    - { src: 'named/named.rfc1912.zones', dest: '/var/named-xs/named.rfc1912.zones' }
    - { src: 'named/named.root', dest: '/var/named-xs/named.root' }
    - { src: 'named/named.root.hints', dest: '/var/named-xs/named.root.hints' }
    - { src: 'named/named.zero', dest: '/var/named-xs/named.zero' }
    - { src: 'named/school.external.zone.db', dest: '/var/named-xs/school.external.zone.db' }
    - { src: 'named/school.internal.zone.16.in-addr.db.j2', dest: '/var/named-xs/school.internal.zone.16.in-addr.db' }
    - { src: 'named/school.internal.zone.32.in-addr.db.j2', dest: '/var/named-xs/school.internal.zone.32.in-addr.db' }
    - { src: 'named/school.internal.zone.48.in-addr.db.j2', dest: '/var/named-xs/school.internal.zone.48.in-addr.db' }
    - { src: 'named/school.internal.zone.db', dest: '/var/named-xs/school.internal.zone.db' }
    - { src: 'named/school.internal.zone.in-addr.db.j2', dest: '/var/named-xs/school.internal.zone.in-addr.db' }
    - { src: 'named/dummy', dest: '/var/named-xs/data/dummy' }
