- name: Configure /etc/sysconfig/network
  template: src=network/sysconfig.network.j2
            dest=/etc/sysconfig/network
            owner=root
            group=root
            mode=0644

- name: Remove lan and wan ifaces from network manager
  ini_file: dest=/etc/NetworkManager/NetworkManager.conf
            section=keyfile
            option=unmanaged-devices
            value=mac:${mac_lan.stdout}
#           value=mac:${mac_lan.stdout};mac:${mac_wan.stdout}
#TODO: when wan is wifi, we can manage it with nm

- name: Configure lan interface
  template: src=network/ifcfg.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-${item.iface}
  with_items:
    - ${xsce_networks.lan}

- name: Configure lan mac address
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-${xsce_networks.lan.iface}
              regexp='^HWADDR='
              line='HWADDR=${mac_lan.stdout}'
              state=present
