- name: Install squid packages
  yum: name=${item}
       state=installed
  with_items:
    - squid
    - cadaver

- name: Copy init script and config file
  template: src=${item.src}
            dest=${item.dest}
            owner=${item.owner}
            group=${item.owner}
            mode=${item.mode}
  with_items:
    - src: 'squid/squid.sysconfig'
      dest: '/etc/sysconfig/squid'
      owner: 'root'
      group: 'root'
      mode: '0755'
    - src: 'squid/squid-xs.conf.j2'
      dest: '/etc/squid/squid-xs.conf'
      owner: 'squid'
      group: 'squid'
      mode: '0644'

- name: Create squid cache directory
  file: path=/library/cache
        owner=squid
        group=squid
        mode=0750
        state=directory

- name: Create xs_httpcache flag
  shell: echo 1 > /etc/sysconfig/xs_httpcache_on
         creates=/etc/sysconfig/xs_httpcache_on

- name: Start squid service
  service: name=squid
           enabled=yes
