- name: Disable sleep
  command: touch /etc/powerd/flags/inhibit-suspend
           creates=/etc/powerd/flags/inhibit-suspend
- name: Keep yum cache
  ini_file: dest=/etc/yum.conf
            section=main
            option=keepcache
            value=1
- name: Disable sleep on lid closing
  lineinfile: dest=/etc/powerd/powerd.conf
              regexp='^config_SLEEP_WHEN_LID_CLOSED' 
              line='config_SLEEP_WHEN_LID_CLOSED="no"'
              state=present
              backup=yes
