- name: Disable sleep
  command: touch /etc/powerd/flags/inhibit-suspend
           creates=/etc/powerd/flags/inhibit-suspend

- name: Disable sleep on lid closing
  lineinfile: dest=/etc/powerd/powerd.conf
              regexp='^config_SLEEP_WHEN_LID_CLOSED' 
              line='config_SLEEP_WHEN_LID_CLOSED="no"'
              state=present
              backup=yes

- name: Keep yum cache
  ini_file: dest=/etc/yum.conf
            section=main
            option=keepcache
            value=1

- name: Configure networkmanager plugin
  ini_file: dest=/etc/NetworkManager/NetworkManager.conf
            section=main
            option=plugins
            value=keyfile

- name: Create modem connection
  template: src=templates/xo/networkmanager-modem
            dest=/etc/NetworkManager/system-connections/"Sugar Modem Connection"
            owner=root
            group=root
            mode=0600

