- name: Get XSCE facts
  xsce_facts: facts=true
  tags: 
    - activity-server
    - addons
    - ajenti
    - authserver
    - avahi
    - base
    - dhcpd
    - download
    - edu-apps
    - ejabberd
    - facts
    - gateway
    - httpd
    - idmgr
    - iiab
    - monit
    - moodle
    - munin
    - named
    - network
    - olpc
    - pathagar
    - portal
    - postgresql
    - preliminaries
    - services
    - squid
    - sugar-stats
    - tools
    - wondershaper
    - xo
    - xo-services

- name: Set hostname
  template: backup=yes
            dest=/etc/hostname
            src=hostname.j2
            owner=root
            mode=0644

- name: Install xsce-release and xsce-extra repos
  get_url: url={{ item }} dest=/etc/yum.repos.d/
  tags:
    - download
  with_items:
    - http://download.unleashkids.org/xsce/repos/xsce-release.repo
    - http://download.unleashkids.org/xsce/repos/xsce-extra.repo


- name: Install custom profile file
  template: dest=/etc/profile.d/zzz_xsce.sh
            src=zzz_xsce.sh
            owner=root
            mode=0644
            backup=yes

- name: Create /library
  file: path=/library
        owner=root
        group=root
        mode=0755
        state=directory

- name: Disable root login with password 
  lineinfile: backup=yes
              dest=/etc/ssh/sshd_config
              regexp='^PermitRootLogin'
              line='PermitRootLogin without-password'
              state=present
#TODO: use handler to reload ssh

- name: Enable common services
  service: name={{ item }}
           enabled=yes
           state=restarted
  with_items:
    - sshd
