- name: Install awstats package
  yum: pkg={{ item }} state=installed
  with_items:
    - awstats
    - mod_ssl
    - mod_authnz_external
    - pwauth
  tags:
    - download

- name: Create directory for awstat to use as intermediate summary storage
  file: path={{ item }}
        mode=0755
        owner=apache
        group=apache
        state=directory
  with_items:
    - "{{ awstats_data_dir }}"

- name: Install the Apache config for Advanced Web Statistics 
  template: src=apache-awstats.conf
            dest=/etc/httpd/conf.d/awstats.conf
            owner=root
            group=root
            mode=0644
  when: awstats_enabled

- name: Install the awstats config for Advanced Web Statistics 
  template: src=awstats.schoolserver.conf.j2
            dest=/etc/awstats/awstats.schoolserver.conf
            owner=root
            group=root
            mode=0644
  when: awstats_enabled

- name: Create a symbolic link to use when access is by ip address
  file: src=/etc/awstats/awstats.schoolserver.conf
        dest=/etc/awstats/awstats.conf
        state=link
  when: awstats_enabled

- name: On first enabling of awstats, summarize httpd logs up to now
  shell: /usr/bin/perl /usr/share/awstats/wwwroot/cgi-bin/awstats.pl -config=schoolserver -update
  when: awstats_enabled

- name: remove config file when it is disabled
  file: dest=/etc/httpd/conf.d/awstats.schoolserver.conf
        state=absent
  when: not awstats_enabled

- name: change the log format of squid to be compatible with awstats
  lineinfile: line='logformat combined %>a %ui %un [%{%d/%b/%Y:%H:%M:%S +0000}tl] "%rm %ru HTTP/%rv" %Hs %<st "%{Referer}>h" "%{User-Agent}>h" %Ss:%Sh'
              dest=/etc/squid/squid-xs.conf
  when: False 

- name: select this format
  lineinfile: dest=/squid/squid-xs.conf
              line="access_log /var/log/squid3/access.log combined"
  when: False
