- name: gui_static_wan
  set_fact:
    wan_ip: dhcp
    gui_static_wan_ip: undefined
  when: gui_static_wan is defined and gui_static_wan == "False"

- name: Using GUI_STATIC info
  set_fact:
    wan_ip: "{{ gui_static_wan_ip }}"
    wan_netmask: "{{ gui_static_wan_netmask }}"
    wan_gateway: "{{ gui_static_wan_gateway }}"
    wan_nameserver: "{{ gui_static_wan_nameserver }}"
  when: gui_static_wan_ip != "unset" and gui_static_wan_ip != "undefined" and gui_static_wan is defined 

# OK try old gw this is a best guess based on what's in /etc/sysconfig/xs_wan_device's last state
# intended to provide a seed value to display in the GUI when no gateway is present but we had one.
- name: Has old gateway and no discovered gateway setting WAN
  set_fact:
    gui_wan_iface: "{{ had_gw }}"
  when: user_wan_iface == "auto" and had_gw != "none" and discovered_wan_iface == "none"

# need to add this field in the GUI
# we need to have an interface name for ifcfg-WAN to be able to change gateway the DEVICE from the gui.
- name: Using GUI_WAN info
  set_fact:
    user_wan_iface: "{{ gui_wan_iface }}"
  when: gui_wan_iface != "unset"

# should make the GUI buttons the last call
- name: Checking xsce_wan_enabled
  set_fact:
    user_wan_iface: "none"
  when: 'not xsce_wan_enabled'

# override with user_wan_iface setting if no longer in auto
- name: setting user WAN fact
  set_fact:
    xsce_wan_iface: "{{ user_wan_iface }}"
  when: user_wan_iface != "auto"

# user disabled interface - overriding all other entries
- name: Checking xsce_lan_enabled
  set_fact:
    user_lan_iface: "none"
  when: 'not xsce_lan_enabled'

# gui wants Appliance
- name: Setting GUI wants Appliance
  set_fact:
    user_lan_iface: "none"
  when: gui_desired_network_role is defined and gui_desired_network_role == "Appliance"

# override with user_lan_iface setting if no longer in auto
- name: Setting user LAN fact
  set_fact:
    xsce_lan_iface: "{{ user_lan_iface }}"
  when: 'user_lan_iface != "auto"'

- name: No LAN configured - Appliance mode
  set_fact:
    dansguardian_enabled: False
    squid_enabled: False
    named_enabled: True
    dhcpd_enabled: False
    wondershaper_enabled: False
    xsce_network_mode: "Appliance"
  when: xsce_lan_iface == "none" or user_lan_iface == "none"

- name: LAN configured - LanController mode
  set_fact:
    named_enabled: True
    dhcpd_enabled: True
    dansguardian_enabled: False
    squid_enabled: False
    wondershaper_enabled: False
    xsce_network_mode: "LanController"
  when: xsce_lan_iface != "" and xsce_wan_iface == "none"

- name: LAN configured - Gateway mode
  set_fact:
    named_enabled: True
    dhcpd_enabled: True
    xsce_network_mode: "Gateway"
  when: 'xsce_lan_iface != "none" and xsce_wan_iface != "none"'

- name: Add location section to config file
  ini_file: dest='{{ xsce_config_file }}'
            section=network
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
  - option: 'wan_enabled'
    value: '{{ xsce_wan_enabled }}'
  - option: 'user_gateway'
    value: '{{ user_wan_iface }}'
  - option: 'computed_gateway'
    value: '{{ xsce_wan_iface }}'
  - option: 'lan_enabled'
    value: '{{ xsce_lan_enabled }}'
  - option: 'user_lan'
    value: '{{ user_lan_iface }}'
  - option: 'computed_lan'
    value: '{{ xsce_lan_iface }}'
  - option: 'xsce_network_mode_applied'
    value: '{{ xsce_network_mode }}'
