- name: Stop the Access Point Hostapd program
  service: name=hostapd.service
           state=stopped
  when: xsce_wireless_lan_iface != "none"

# Disconnects the slaves quickly
- name: Stop the LAN/Bridge on F21
  shell: nmcli con delete id xsce-LAN
  changed_when: False
  when: num_lan_interfaces != "0" and xsce_wireless_lan_iface != "0"

# clear all non WAN ifcfg files
- name: Now delete all non-gateway ifcfg files
  shell: "rm -f {{ item }} "
  when: item|trim != device_gw and num_lan_interfaces != "0"
  with_items:
    - "{{ ifcfg_files.stdout_lines }}"

# comment out Using GUI_WAN info and un-comment below
## yet to come but device_gw is the first one to test.
## vars/ users should set user_wan_iface to avoid messy redetect 
- include: redetect.yml  
  when: discovered_wan_iface == "none" and user_wan_iface == "auto"

# move gateway if not WAN
# might have wifi info if wireless is used as uplink.
- include: edit_ifcfg.yml
  when: has_ifcfg_gw != "none" and has_ifcfg_gw != "/etc/sysconfig/network-scripts/ifcfg-WAN"

# create ifcfg-WAN if missing
# if we get here we have gateway but no ifcfg file
- include: create_ifcfg.yml
  when: xsce_wan_iface != "none" and not has_WAN and has_ifcfg_gw == "none"

- name: Configuring LAN interface as xsce_lan_iface
  template: src=network/ifcfg.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-LAN
  when: xsce_lan_iface != "none"

# can be more than one wired interface
- name: Wired enslaving ## lan_list_result ## to Bridge
  template: src=network/ifcfg-slave.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{ item|trim }}
  when: xsce_lan_iface == "br0" and item|trim != xsce_wireless_lan_iface and item|trim != device_gw
  with_items:
      - "{{ lan_list_result.stdout_lines }}"

- name: WiFi enslaving {{ xsce_wireless_lan_iface }} to Bridge
  template: src=network/wifi-slave.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{ xsce_wireless_lan_iface }}
  when: xsce_lan_iface == "br0" and xsce_wireless_lan_iface != "none"
  tags:
    - network

- include: enable_wan.yml
  when: not installing

# monitor-connection-files defaults to no with F21, F18-F20 defaults to yes
- name: Re-read network config files
  shell: nmcli con reload
  when: not installing and not no_NM_reload

# test point, we should always have one with any kind of starting point 
# no ifcfg = supply
# had but not WAN = rename and edit.
# test point, confirm onboot=no is OK everywhere

- name: Enabling pre-existing ifcfg-WAN file
  shell: nmcli conn up id xsce-WAN
  when: has_WAN and xsce_wan_iface != "none" and not installing

- name: Enabling ifcfg-LAN file
  shell: nmcli conn up id xsce-LAN
  when: xsce_lan_iface != "none" and not installing
# testpoint confirm with 'nmcli c show' 'brctl show'

