- name: Disable firewalld service
  service: name=firewalld
           enabled=no

- name: Use larger hammer to disable firewalld (2 symbolic links involved)
  shell: "systemctl disable firewalld.service"

- name: Mask firewalld service
  shell: 'systemctl mask firewalld'

- name: Stop firewalld service
  service: name=firewalld
           state=stopped
  ignore_errors: yes
  when: not installing

- name: Remove iptables.service file from /etc
  file: path=/etc/systemd/system/iptables.service 
        state=absent

- name: Remove iptables-xs.service file from /etc
  file: path=/etc/systemd/system/iptables-xs.service 
        state=absent

- name: Install iptables service package
  yum: name=iptables-services
       state=installed
  tags:
    - download

- name: Install iptables services
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner={{ item.owner }}
            group={{ item.group }}
            mode={{ item.mode }}
  with_items:
   - src: 'gateway/iptables-config'
     dest: '/etc/sysconfig/iptables-config'
     owner: 'root'
     group: 'root'
     mode: '0644'

