- name: Create olpc-scripts directory
  file: path={{ item }}
        owner=root
        group=root
        mode=0755
        state=directory
  with_items:
    - /etc/sysconfig/olpc-scripts/
    - /etc/sysconfig/olpc-scripts/setup.d/installed/

- name: Create xs network flags
  template: backup=yes
            src=network/{{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - xs_wan_device
    - xs_lan_device
    - xs_domain_name
  tags:
    - network-discover

- name: Configure /etc/sysconfig/network
  template: backup=yes
            src=network/sysconfig.network.j2
            dest=/etc/sysconfig/network
            owner=root
            group=root
            mode=0644

#TODO: Use vars instead of hardcoded values
- name: Configure /etc/hosts
  lineinfile: backup=yes
              dest=/etc/hosts
              regexp='^172\.18\.96\.1'
              line='172.18.96.1            {{ xsce_hostname }}.{{ xsce_domain }}      {{ xsce_hostname }}'
              owner=root
              group=root
              mode=0644

- name: Configure /etc/hosts
  lineinfile: backup=yes
              dest=/etc/hosts
              regexp='^127\.0\.0\.1'
              line='127.0.0.1            localhost.localdomain   localhost   {{ xsce_hostname }}'
              owner=root
              group=root
              mode=0644


- name: Configure lan interface
  template: backup=yes
            src=network/ifcfg.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{xsce_lan_iface}}
  when: 'xsce_lan_iface != "none"'

- include: named.yml
  tags:
    - named
    - network

- include: dhcpd.yml
  tags:
    - dhcpd
    - network

- include: squid.yml
  tags:
    - squid
    - network

- include: wondershaper.yml
  tags:
    - wondershaper
    - network

- include: iptables.yml
  tags:
    - iptables
    - network

- name: Create gateway flag
  shell: echo 1 > /etc/sysconfig/olpc-scripts/setup.d/installed/gateway
         creates=/etc/sysconfig/olpc-scripts/setup.d/installed/gateway

- include: NM.yml
  tags:
    - network
  
