# This is a dog's breakfast, but with ansible 1.6.3 service: name=NetworkManager state=restarted doesn't work

- name: restart NetworkManager services
  service: name=NetworkManager
           enabled=yes
           state=stopped
- service: name=NetworkManager-dispatcher
           enabled=yes
           state=stopped
- wait_for: path=/etc/passwd
            delay=4
            timeout=5
- service: name=NetworkManager
           enabled=yes
           state=started
- wait_for: path=/etc/passwd
            delay=4
            timeout=5
- service: name=NetworkManager-dispatcher
           enabled=yes
           state=started
- debug:  msg="hopefully now NM is restarted"

- include: named.yml
  tags:
    - named
    - network

- include: dhcpd.yml
  tags:
    - dhcpd
    - network

- include: squid.yml
  tags:
    - squid
    - network

- include: wondershaper.yml
  tags:
    - wondershaper
    - network

- include: iptables.yml
  tags:
    - iptables
    - network

- name: Create gateway flag
  shell: echo 1 > /etc/sysconfig/olpc-scripts/setup.d/installed/gateway
         creates=/etc/sysconfig/olpc-scripts/setup.d/installed/gateway

