# Too do handle more than one detected interface
- name: Turn off NM for {{discovered_wireless_iface}}
  lineinfile: state=present
              backrefs=yes
              regexp="NM_CONTROLLED"
              line="NM_CONTROLLED=no"
              dest=/etc/sysconfig/network-scripts/ifcfg-{{discovered_wireless_iface}}
  when: xsce_lan_iface == "br0"

- name: Turn off NM for LAN
  lineinfile: state=present
              backrefs=yes
              regexp="NM_CONTROLLED"
              line="NM_CONTROLLED=no"
              dest=/etc/sysconfig/network-scripts/ifcfg-LAN
  when: xsce_lan_iface == "{{ xsce_wireless_lan_iface }}"

