# Too do handle more than one detected interface
- name: Turn off NM for {{discovered_wireless_iface}}
  lineinfile: state=present
              backrefs=yes
              regexp="NM_CONTROLLED"
              line="NM_CONTROLLED=no"
              dest=/etc/sysconfig/network-scripts/ifcfg-{{discovered_wireless_iface}}

- name: Enable network.service for non-bridged Wifi
  service: name=network
  enabled=yes
  state=restarted
  when: xsce_lan_iface != "br0"

- name: Disable network.service for bridged Wifi
  service: name=network
  enabled=no
  state=stopped
  when: xsce_lan_iface == "br0"

