# Setup specific to the Raspberry Pi
#
- name: Put a bash script to bring up rpi network with hostapd AP
  template: src=hostapd/up-rpi.j2
            dest=/usr/local/sbin/up-rpi
            mode=0755
            owner=root
            group=root
  when: xsce_network_mode != "Appliance" and xsce_wireless_lan_iface != "none"

- name: Add a line in rc.local to execute up-rpi network script
  lineinfile: backup=yes
              line="/usr/local/sbin/up-rpi"
              dest=/etc/rc.d/rc.local
  when: xsce_network_mode != "Appliance" and xsce_wireless_lan_iface != "none"

- name: Remove the line in rc.local that executes up-rpi network script
  lineinfile: state=absent
              regexp="/usr/sbin/up-rpi"
              dest=/etc/rc.d/rc.local
  when: xsce_network_mode == "Appliance" or xsce_wireless_lan_iface == "none"
