- name: Start named service
  service: name=named
           state=started
  when: named_enabled

- name: Restart dansguardian
  service: name=dansguardian
           state=restarted
  when: dansguardian_enabled

- name: Enable squid service
  service: name=squid
           state=restarted
  when: squid_enabled

- name: Enable wondershaper service
  service: name=wondershaper
            state=restarted
  when: wondershaper_enabled
