- name: Install avahi package
  yum: name={{ item }}
       state=present
  with_items:
   - nss-mdns
   - avahi
   - avahi-tools
   - avahi-ui
  tags:
    - download

- name: Install avahi announce config files
  template: backup=yes
            src=schoolserver.service
            dest=/etc/avahi/services/schoolserver.service
            owner=avahi
            group=avahi
            mode=640
  when: 'gui_wan == "True"'

- name: set ssh port for avahi
  lineinfile: dest=/etc/avahi/services/ssh.service
              regexp='^<port>'
              line='<port>{{ssh_port}}</port>'
              state=present

- name: Enable avahi service
  service: name=avahi-daemon
           enabled=yes
           state="restarted"
