- include: prelim.yml

- include: yum.yml 
  tags:
    - download

- include: fedora.yml
  when: ansible_distribution == "Fedora"
    - download

- include: chrony.yml
- include: avahi.yml
- include: sysctl.yml
