- name: Install chrony package
  yum: name=$item
       state=present
  with_items:
   - chrony

#TODO: Use regexp filter instead of hard-code ip 
- name: Update chrony config file
  template: backup=yes
            dest=/etc/chrony.conf
            src=chrony.conf.j2

