# get local vars from scripts in /etc/ansible/facts.d

- name: create ansible.d facts directory
  file: path=/etc/ansible/facts.d
        owner=root
        group=root
        mode=0750
        state=directory

- name: local facts script
  template: backup=yes
            src=local_facts.fact.j2
            dest=/etc/ansible/facts.d/local_facts.fact
            owner=root
            group=root
            mode=0700

- name: re-read facts
  setup: filter=ansible_local

# set top level variables from local facts for convenience
- set_fact:
     phplib_dir: '{{ ansible_local["local_facts"]["phplib_dir"] }}'

# Put all computed vars here so derive properly from any prior var file

- name: Turn on mysql if elgg or rachel enabled
  set_fact:
    mysql_enabled: True
  when: elgg_enabled or rachel_enabled

# for various reasons the mysql service can not be enabled on fedora 20,
# but 'mariadb', which is its real name can
# on fedora 18 we need to use 'mysqld'
      
- name: Set mysqld service name to mariadb by default
  set_fact:
    mysql_service: mariadb
    
- name: Set mysqld service name to mysqld for fedora 18
  set_fact:
    mysql_service: mysqld    
  when: ansible_distribution_release == "based on Fedora 18"
                  