##  DISCOVER PLATFORMS ######
- name: Discover if this is a rpi2 -- if so it has a bcm2709 processor
  set_fact: 
     rpi_model: "rpi2"
  when:  ansible_cmdline["bcm2709.serial"]  is defined
  ignore_errors: true


- include: hw_rpi2.yml
