- include: hw_discovery.yml
- include: computed_vars.yml
- include: detected_network.yml
  when: not installing
- include: raspberry_pi_2.yml
  when: rpi_model != "none"
- include: fix_ansible_version.yml
  when: not gui_version is defined or xsce_base_ver < 1
