- include: prep.yml
- include: computed_vars.yml
           always_run: yes
           
# Put conditional includes for platforms here
- include: xo.yml
  when: ansible_distribution_release == "based on Fedora 18"
  tags:
    - xo
