- name: Get XSCE facts
  xsce_facts: facts=true
  tags: 
    - facts
    - prep
    - platform
    - common
    - base
    - options
    - xo-services
    - generic-apps
    - edu-apps
    - tools
    - addons

- name: Set hostname
  template: backup=yes
            dest=/etc/hostname
            src=hostname.j2
            owner=root
            mode=0644

- name: Install xsce-release and xsce-extra repos
  get_url: url={{ item }} dest=/etc/yum.repos.d/
  tags:
    - download
  with_items:
    - http://download.unleashkids.org/xsce/repos/xsce-release.repo
    - http://download.unleashkids.org/xsce/repos/xsce-extra.repo
