- name: Set hostname
  template: backup=yes
            dest=/etc/hostname
            src=hostname.j2
            owner=root
            mode=0644

- name: Install xsce-release and xsce-extra repos
  get_url: url={{ item }} dest=/etc/yum.repos.d/
  tags:
    - download
  with_items:
    - http://download.unleashkids.org/xsce/repos/xsce-release.repo
    - http://download.unleashkids.org/xsce/repos/xsce-extra.repo
    - http://download.unleashkids.org/xsce/repos/xsce-testing.repo

- name: create ansible.d facts directory
  file: path=/etc/ansible/facts.d
        owner=root
        group=root
        mode=0750
        state=directory

- name: local facts script
  template: backup=yes
            src=local_facts.fact.j2
            dest=/etc/ansible/facts.d/local_facts.fact
            owner=root
            group=root
            mode=0700

- name: re-read facts
  setup: filter=ansible_local
                  