# Setup specific to the Raspberry Pi
#
- name: Set default facts for rpi device detection
  set_fact:
    wifi_id: none
    rtc_chip: none

- name: Load the modules for the RTC
  template: dest=/etc/modules-load.d/rtc.conf
            src=rtc.conf

- name: Install packages needed by rpi2
  yum:  name={{ item }}
        state=present
  with_items:
        - i2c-tools
        - bridge-utils
        - usbutils

- name: sense the usb wifi if it exists
  shell: "lsusb | grep 0bda:8179 | wc |gawk '{print $1}'"
  register: usb_response
  ignore_errors: true

- name: Use compiled hostapd, and wpa_supplicant if tplink WM725M
  set_fact:
     wifi_id: tplink_WM725M
  when:  usb_response.stdout|int > 0

- name: Install the standard hostapd if possible
  yum:  name={{ item }}
        state=present
  when: wifi_id  ==  "none"
  with_items:
       - hostapd_8188
       - wpa_supplicant_8188
 
- name: Download substitute software
  get_url: url="{{ xsce_download_url }}/{{ item }}"  dest={{ downloads_dir}}/{{ item }}
  when: wifi_id  ==  "tplink_WM725M" and not {{ use_cache }} and not {{ no_network }}
  with_items:
     - hostapd_8188
     - wpa_supplicant_8188

- name: Put the substitute files in place
  copy: src={{ downloads_dir }}/hostapd_8188
        dest=/usr/sbin/hostapd
        backup=yes
        mode=0775
        owner=root
        group=root
  when: wifi_id  ==  "tplink_WM725M"

- name: Put the substitute wpa_supplicant in place
  copy: src={{ downloads_dir }}/wpa_supplicant_8188
        dest=/usr/sbin/wpa_supplicant
        backup=yes
        mode=0775
        owner=root
        group=root
  when: wifi_id  ==  "tplink_WM725M"

- name: Detect an i2c rtc if it exists
  shell: "i2cdetect | grep -e 68 -e UU | wc | gawk '{print $1}'"
  register: rtc_response
  ignore_errors: yes

- name: Record whether rtc hardware was detected
  set_fact:
     wifi_id: rtc_id = "DS3231"
  when:  rtc_response.stdout|int > 0


- name: Instantiate a connection to i2c RTC
  lineinfile: dest=/etc/rc.d/rc.local
              line="echo ds3231 0x68 > /sys/class/i2c-adapter/i2c-1/new_device"
              create=yes
  when: rtc_id == "DS3231" 

- name: in rc.local start the network again
  lineinfile: dest=/etc/rc.d/rc.local
              line='systemctl restart NetworkManager.service'

- name: in rc.local attach dhcpd to new device
  lineinfile: dest=/etc/rc.d/rc.local
              line='systemctl restart dhcpd.service'

- name: in rc.local start up access point software
  lineinfile: dest=/etc/rc.d/rc.local
              line='/usr/local/bin/hostapd -B /etc/hostapd/hostapd.conf'

- name: in rc.local attach new device to bridge
  lineinfile: dest=/etc/rc.d/rc.local
              line='brctl addif br0 wlan0'

