# Setup specific to the Raspberry Pi
#
- name: Load the modules for the RTC
  template: dest=/etc/modules-load.d/rtc.conf
            src=rtc.conf

- name: Install packages needed by rpi2
  yum:  name={{ item }}
        state=present
  with_items:
        - i2c-tools
        - bridge-utils

- name: Install the standard hostapd if possible
  yum:  name=hostapd
        state=present
  when: hostapd ==  ""

- name: Instantiate a connection to i2c RTC
  lineinfile: dest=/etc/rc.d/rc.local
              line="echo ds3231 0x68 > /sys/class/i2c-adapter/i2c-1/new_device"
              create=yes

- name: in rc.local start the network again
  lineinfile: dest=/etc/rc.d/rc.local
              line='systemctl restart network.service'

- name: in rc.local attach dhcpd to new device
  lineinfile: dest=/etc/rc.d/rc.local
              line='systemctl restart dhcpd.service'

- name: in rc.local start up access point software
  lineinfile: dest=/etc/rc.d/rc.local
              line='/usr/local/bin/hostapd -B /etc/hostapd/hostapd.conf'

- name: in rc.local attach new device to bridge
  lineinfile: dest=/etc/rc.d/rc.local
              line='brctl addif br0 wlan0'

- name: download hostapd and wpa-supplicant
  get_url: url="{{ xsce_download_url }}/{{ hostapd }}" dest={{ downloads_dir }}/{{ hostapd }}
  when: hostapd != ""

- name: download  wpa-supplicant
  get_url: url="{{ xsce_download_url }}/{{ wpa_supplicant }}" dest={{ downloads_dir }}/{{ wpa_supplicant }}
  when: wpa_supplicant != ""

- name: put the downloaded wifi Access Point files on PATH
  copy: src={{ downloads_dir }}/{{ hostapd }} dest=/usr/local/sbin/{{ hostapd }}
  when: hostapd != ""

- name: put the downloaded wifi Access Point authentication files on PATH
  copy: src={{ downloads_dir }}/{{ wpa_supplicant }} dest=/usr/local/sbin/{{ wpa_supplicant }}
  when: wpa_supplicant !=  ""
