- name: Install IIAB required packages
  yum: name={{ item }}
       state=present
  with_items:  
    - python-pip 
    - gcc 
    - python-devel 
    - python-setuptools
    - xz-devel 
    - mod_wsgi   
    - mod_xsendfile
  tags:
    - download
    
- name: Install latest MarkupSafe
  pip: name=MarkupSafe
       state=latest       
       
- name: Install IIAB with pip
  pip: name=Internet-in-a-Box
       state=latest
       extra_args="-b /piptmp"
    
- name: Copy IIAB config file
  template: backup=yes
            src=iiab.conf.j2
            dest=/etc/httpd/conf.d/iiab.conf
            owner=root
            group=root
            mode=0644

- name: Create link to cgi 
  file: src=/bin/iiab.wsgi
        dest=/var/www/html/iiab.wsgi
        owner=root
        group=root
        state=link

- name: Restart httpd service
  service: name=httpd
           state=restarted

- name: add iiab to service list
  ini_file: dest='{{ service_filelist }}'
            section=iiab
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
    - option: name
      value: Internet-in-a-Box
    - option: description
      value: "The Internet-in-a-Box is a small, inexpensive device which provides essential Internet resources without any Internet connection. It provides a local copy of half a terabyte of the world’s Free information."
    - option: path
      value: /iiab
