# This chould go in computed_network.yml, but here for now

- name: Compute owncloud listen ip addr for owncloud.conf
  set_fact:
     owncloud_required_ip: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
  when: ansible_default_ipv4.network is defined

- name: Enable owncloud by copying template to httpd config
  template: src=owncloud.conf.j2
            dest=/etc/httpd/conf.d/owncloud.conf
            owner=root
            group=root
            mode=0644

- name: Restart apache, so it picks up the new aliases
  service: name=httpd state=restarted

- name: Run owncloud initial install wizard
  shell: curl http://{{ xsce_hostname }}{{ owncloud_url }}/index.php

- name: Remove Rewrite URL
  lineinfile: regexp='overwrite.cli.url'
              state=absent
              dest="{{ owncloud_path }}/config/config.php"

# This is very version dependent

- name: Remove Trusted Domains - comment before
  lineinfile: dest="{{ owncloud_path }}/config/config.php"
              insertbefore='trusted_domains'
              line='/*'
              state=present

- name: Remove Trusted Domains - comment after
  lineinfile: dest="{{ owncloud_path }}/config/config.php"
              insertafter='\),'
              line='*/'
              state=present
